language: php
sudo: false
php:
  - 7.1
  - 7.2
  - 7.3
env:
  - PHPUNIT=^6.0
  - PHPUNIT=^7.0
  - PHPUNIT=^8.0
matrix:
  exclude:
    - php: 7.1
      env: PHPUNIT=^8.0
install:
  - pecl install --force mongodb
  - composer require --no-update --no-interaction --no-ansi phpunit/phpunit $PHPUNIT
  - composer install --no-interaction --no-ansi --prefer-dist
script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
after_success:
  - vendor/bin/test-reporter
