language: php
sudo: false
php:
  - 7.0
install:
  - pecl install mongodb
  - composer install --prefer-dist
script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
after_success:
  - vendor/bin/test-reporter
