version: "3"
services:
  php7phpunit:
    build:
      context: .
      dockerfile: php7phpunit.DOCKERFILE
    command:
      - bash
      - -c
      - |
        composer update
        vendor/bin/phpunit
    working_dir: /work
    volumes:
       - .:/work

  php8phpunit:
    build:
      context: .
      dockerfile: php8phpunit.DOCKERFILE
    command:
      - bash
      - -c
      - |
        composer update
        vendor/bin/phpunit
    working_dir: /work
    volumes:
       - .:/work